version: '3'
services:
  react-ui:
    build:
      context: .
    ports:
      - "3001:3000"    
    # environment:
    #   - REACT_APP_INTERVAL=10000
    container_name: songs-ui
    stdin_open: true